name = "codegangsta"
license = "MIT"
licenselink = "TODO"
description = "An elegant open source and mobile first theme, extended with new integrations and layout improvements"
homepage = "http://github.com/codegangsta"
tags = ["blog", "technical", "personal"]
features = ["blog", "technical", "personal"]

[author]
    name = "Jeremy Saenz"
    homepage = "http://codegangsta.io"

# If Porting existing theme
[original]
    author =  "Hyde-X"
    homepage = "http://hyde.getpoole.com"
    repo = "https://github.com/poole/hyde"
